apiVersion: argoproj.io/v1alpha1
kind: Experiment
name:
  name: target-service-experiment
  namespace: apex  
spec:
  duration: 10m
  templates:
  - name: baseline
    replicas: 1
    spec:
      containers:
      - name: target-service
        image: parthakonwar/target-service:v1
  - name: canary
    replicas: 1
    spec:
      containers:
      - name: target-service
        image: parthakonwar/target-service:v2
  analysis:
    templateName: kayenta-template
    args:
    - name: start-time
      value: "{{experiment.availableAt}}"
    - name: end-time
      value: "{{experiment.finishedAt}}"